server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.0.7:3306/makxtest
    username: root
    password: disApple1
    driver-class-name: com.mysql.jdbc.Driver
#logging:
#  level:
#    root: debug
